apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: r16a-ares

resources:
  - namespace.yaml
  - pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
