apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ares-data
  namespace: r16a-ares
  labels:
    app.kubernetes.io/name: ares
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
